---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates for Ubuntu
    tags: always
    apt:
     upgrade: dist
     update_cache: yes
    when: ansible_distribution in ["Debian", "Ubuntu"]


  - name: install updates for CentOS
    tags: always
    dnf:
     update_only: yes
     update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: copy default html file for site
    tags: apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

  - name: start httpd service on CentOS
    tags: httpd,apache,centos
    service:
      name: httpd
      state: started
      enabled: yes
    when: ansible_distribution == "CentOS"

  - name: Change email address for admin in httpd file
    tags: httpd,apache,centos
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^ServerAdmin'
      kine: ServerAdmin sombody"somewher.net
    when: ansible_distribution == "CentOS"
    register: httpd

  - name: restart httpd service on CentOS
    tags: httpd,apache,centos
    service:
      name: httpd
      state: restarted
    when: httpd.changed


- hosts: workspace
  become: true
  tasks:
  - name: install unzip
    package:
       name: unzip

  - name: install terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.10.4/terraform_1.10.4_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root


- hosts: web_servers
  become: true
  tasks:

  - name: install apache2 package and php package for Ubuntu
    tags: apache,apache2,ubuntu
    apt:
     name:
       - apache2
       - libapache2-mod-php
     state: latest
    when: ansible_distribution in ["Debian", "Ubuntu"]


  - name: install apache2 package and php for CentOS
    tags: httpd,apache,centos
    dnf:
     name:
       - httpd
       - php
     state: latest
    when: ansible_distribution == "CentOS"


- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb on Ubuntu
    tags: db,mariadb,ubuntu
    apt:
     name:
       - mariadb-server
     state: latest
    when: ansible_distribution in ["Debian", "Ubuntu"]


  - name: install mariadb CentOS
    tags: centos,db,mariadb
    dnf:
     name:
       - mariadb
     state: latest
    when: ansible_distribution == "CentOS"

- hosts: file_servers
  become: true
  tasks:

  - name: install samba package all distro
    tags: samba
    package:
     name: samba
     state: latest



